### PR TITLE
fix: creating entity with null id

### LINKED ISSUE #26: Creating a new entity without ID sends an invalid id as payload
When creating a new entity without supplying an ID, makes a `POST` supplying the ID as `null`, which is not JSON:API compliant

### PR DESCRIPTION
**Pull request by nicobritos**
Fixes #26

### CODE REVIEW

File: lib/src/serializers/json_api.dart [hunk 1]
```diff
@@ -43,6 +42,9 @@ class JsonApiSerializer implements Serializer {
       if (withIncluded) {
         jsonMap['included'] = jsonApiDoc.included;
       }
+      if (jsonApiDoc.id != null) {
```
Comment (Bringoff) [inline lib/src/serializers/json_api.dart:45]: @algodave looks like a valid fix, what do you think?

Comment (algodave) [reply lib/src/serializers/json_api.dart:45]: @Bringoff Totally agree, thanks @nicobritos 👍  🙂
